//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: OpCode.proto
namespace com.gamestudio.tank
{
    [global::ProtoBuf.ProtoContract(Name=@"OpCode")]
    public enum OpCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CODE_PUSH", Value=100001)]
      ERR_CODE_PUSH = 100001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_PING", Value=100002)]
      SYS_PING = 100002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_PONG", Value=100003)]
      SYS_PONG = 100003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROOM_REQUEST", Value=1001)]
      ROOM_REQUEST = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROOM_REQ_RET", Value=1002)]
      ROOM_REQ_RET = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JOIN_ROOM", Value=1003)]
      JOIN_ROOM = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JOIN_ROOM_RET", Value=1004)]
      JOIN_ROOM_RET = 1004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROBOT_DRIVE", Value=1005)]
      ROBOT_DRIVE = 1005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_START", Value=1006)]
      FIGHT_START = 1006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MEM_ADD_NOTIFY", Value=1007)]
      MEM_ADD_NOTIFY = 1007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPERATION", Value=1010)]
      OPERATION = 1010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RPC_REQ", Value=1011)]
      RPC_REQ = 1011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RPC_RET", Value=1012)]
      RPC_RET = 1012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MEM_LEAVE_NOTIFY", Value=1013)]
      MEM_LEAVE_NOTIFY = 1013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_MULTI_INIT", Value=1014)]
      UDP_MULTI_INIT = 1014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MEM_LEAVE", Value=1015)]
      MEM_LEAVE = 1015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_COMPLETE", Value=1016)]
      SCENE_COMPLETE = 1016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_START_COMPLETE", Value=1017)]
      FIGHT_START_COMPLETE = 1017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOOT", Value=2001)]
      SHOOT = 2001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOOT_HIT", Value=2002)]
      SHOOT_HIT = 2002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_STATE_SYNC", Value=2003)]
      PLAYER_STATE_SYNC = 2003
    }
  
}