//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RobotDrive.proto
namespace com.gamestudio.Drive
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RobotDrive")]
  public partial class RobotDrive : global::ProtoBuf.IExtensible
  {
    public RobotDrive() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _moveZ;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"moveZ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moveZ
    {
      get { return _moveZ; }
      set { _moveZ = value; }
    }
    private int _moveX;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"moveX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moveX
    {
      get { return _moveX; }
      set { _moveX = value; }
    }
    private int _direction;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private int _crossDicY;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"crossDicY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int crossDicY
    {
      get { return _crossDicY; }
      set { _crossDicY = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RobotFire")]
  public partial class RobotFire : global::ProtoBuf.IExtensible
  {
    public RobotFire() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _fire;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fire", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fire
    {
      get { return _fire; }
      set { _fire = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"DriveType")]
    public enum DriveType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"robotMove", Value=1)]
      robotMove = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"crossMove", Value=2)]
      crossMove = 2
    }
  
}