//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RoomErrCode.proto
namespace com.gamestudio.tank
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomErrMsg")]
  public partial class RoomErrMsg : global::ProtoBuf.IExtensible
  {
    public RoomErrMsg() {}
    
    private com.gamestudio.tank.RoomErrCode _errCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.gamestudio.tank.RoomErrCode errCode
    {
      get { return _errCode; }
      set { _errCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"RoomErrCode")]
    public enum RoomErrCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PASS_WORD_INVALID", Value=1001)]
      PASS_WORD_INVALID = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROOM_MEM_FULL", Value=1002)]
      ROOM_MEM_FULL = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROOM_NOT_ALLOW_OTHERS", Value=1003)]
      ROOM_NOT_ALLOW_OTHERS = 1003
    }
  
}