//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Room.proto
using System;
using com.gamestudio.cs;

namespace com.gamestudio.tank
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UdpMultiNotify")]
  public partial class UdpMultiNotify : global::ProtoBuf.IExtensible
  {
    public UdpMultiNotify() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomHost")]
  public partial class RoomHost : global::ProtoBuf.IExtensible
  {
    public RoomHost() {}
    
    private string _ip;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private int _port;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int port
    {
      get { return _port; }
      set { _port = value; }
    }
    private com.gamestudio.tank.RoomStatus _roomStatus;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.gamestudio.tank.RoomStatus roomStatus
    {
      get { return _roomStatus; }
      set { _roomStatus = value; }
    }
    private bool _isNeedPassWord;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"isNeedPassWord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isNeedPassWord
    {
      get { return _isNeedPassWord; }
      set { _isNeedPassWord = value; }
    }
    private readonly global::System.Collections.Generic.List<com.gamestudio.tank.RoomMem> _members = new global::System.Collections.Generic.List<com.gamestudio.tank.RoomMem>();
    [global::ProtoBuf.ProtoMember(5, Name=@"members", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.gamestudio.tank.RoomMem> members
    {
      get { return _members; }
    }
  
    private string _name;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private com.gamestudio.tank.RoomType _roomType;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.gamestudio.tank.RoomType roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private int _roomSize = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"roomSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomSize
    {
      get { return _roomSize; }
      set { _roomSize = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomRequest")]
  public partial class RoomRequest : global::ProtoBuf.IExtensible
  {
    public RoomRequest() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomResponse")]
  public partial class RoomResponse : global::ProtoBuf.IExtensible
  {
    public RoomResponse() {}
    
    private bool _exist;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"exist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool exist
    {
      get { return _exist; }
      set { _exist = value; }
    }
    private com.gamestudio.tank.RoomHost _room = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"room", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.gamestudio.tank.RoomHost room
    {
      get { return _room; }
      set { _room = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinRoom")]
  public partial class JoinRoom : global::ProtoBuf.IExtensible
  {
    public JoinRoom() {}
    
    private string _password = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _joinCamp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"joinCamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int joinCamp
    {
      get { return _joinCamp; }
      set { _joinCamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinRoomRet")]
  public partial class JoinRoomRet : global::ProtoBuf.IExtensible
  {
    public JoinRoomRet() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private com.gamestudio.tank.RoomHost _room;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.gamestudio.tank.RoomHost room
    {
      get { return _room; }
      set { _room = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartFight")]
  public partial class StartFight : global::ProtoBuf.IExtensible
  {
    public StartFight() {}
    
    private long _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MemAddNotify")]
  public partial class MemAddNotify : global::ProtoBuf.IExtensible
  {
    public MemAddNotify() {}
    
    private com.gamestudio.tank.RoomMem _member;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"member", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.gamestudio.tank.RoomMem member
    {
      get { return _member; }
      set { _member = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MemLeaveNotify")]
  public partial class MemLeaveNotify : global::ProtoBuf.IExtensible
  {
    public MemLeaveNotify() {}
    
    private com.gamestudio.tank.RoomMem _member;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"member", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.gamestudio.tank.RoomMem member
    {
      get { return _member; }
      set { _member = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomMem")]
  public partial class RoomMem : global::ProtoBuf.IExtensible
  {
    public RoomMem() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _camp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int camp
    {
      get { return _camp; }
      set { _camp = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _ip;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private int _campIndex = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"campIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int campIndex
    {
      get { return _campIndex; }
      set { _campIndex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Operation")]
  public partial class Operation : global::ProtoBuf.IExtensible
  {
    public Operation() {}
    
    private int _operCmd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"operCmd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int operCmd
    {
      get { return _operCmd; }
      set { _operCmd = value; }
    }
    private byte[] _operData = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"operData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] operData
    {
      get { return _operData; }
      set { _operData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RPCReq")]
  public partial class RPCReq : global::ProtoBuf.IExtensible
  {
    public RPCReq() {}
    
    private string _rpcName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rpcName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string rpcName
    {
      get { return _rpcName; }
      set { _rpcName = value; }
    }
    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RPCResp")]
  public partial class RPCResp : global::ProtoBuf.IExtensible
  {
    public RPCResp() {}
    
    private string _rpcName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rpcName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string rpcName
    {
      get { return _rpcName; }
      set { _rpcName = value; }
    }
    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MemLeave")]
  public partial class MemLeave : global::ProtoBuf.IExtensible
  {
    public MemLeave() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"RoomStatus")]
    public enum RoomStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PREPARE", Value=1)]
      PREPARE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WAITING_PLAYER", Value=2)]
      WAITING_PLAYER = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHTING", Value=3)]
      FIGHTING = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RoomType")]
    public enum RoomType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SINGLE_PVE", Value=1)]
      SINGLE_PVE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MULTI_PVE", Value=2)]
      MULTI_PVE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP", Value=3)]
      PVP = 3
    }
  
}