//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CS.proto
// Note: requires additional types generated from: Sys.proto
namespace com.gamestudio.cs
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MFightUnit")]
  public partial class MFightUnit : global::ProtoBuf.IExtensible
  {
    public MFightUnit() {}
    
    private int _unitId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"unitId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int unitId
    {
      get { return _unitId; }
      set { _unitId = value; }
    }
    private int _birthIndex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"birthIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int birthIndex
    {
      get { return _birthIndex; }
      set { _birthIndex = value; }
    }
    private int _curIndex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"curIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int curIndex
    {
      get { return _curIndex; }
      set { _curIndex = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _height = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int height
    {
      get { return _height; }
      set { _height = value; }
    }
    private int _camp = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int camp
    {
      get { return _camp; }
      set { _camp = value; }
    }
    private int _health = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"health", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int health
    {
      get { return _health; }
      set { _health = value; }
    }
    private com.gamestudio.cs.UnitType _unitType = com.gamestudio.cs.UnitType.PLAYER;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"unitType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.gamestudio.cs.UnitType.PLAYER)]
    public com.gamestudio.cs.UnitType unitType
    {
      get { return _unitType; }
      set { _unitType = value; }
    }
    private long _deadTime = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"deadTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long deadTime
    {
      get { return _deadTime; }
      set { _deadTime = value; }
    }
    private long _rebirthTime = default(long);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"rebirthTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long rebirthTime
    {
      get { return _rebirthTime; }
      set { _rebirthTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DriverInfo")]
  public partial class DriverInfo : global::ProtoBuf.IExtensible
  {
    public DriverInfo() {}
    
    private int _unitId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"unitId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int unitId
    {
      get { return _unitId; }
      set { _unitId = value; }
    }
    private com.gamestudio.cs.MVector _leftPos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"leftPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.gamestudio.cs.MVector leftPos
    {
      get { return _leftPos; }
      set { _leftPos = value; }
    }
    private com.gamestudio.cs.MVector _rightPos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rightPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.gamestudio.cs.MVector rightPos
    {
      get { return _rightPos; }
      set { _rightPos = value; }
    }
    private com.gamestudio.cs.MVector _headPos;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"headPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.gamestudio.cs.MVector headPos
    {
      get { return _headPos; }
      set { _headPos = value; }
    }
    private com.gamestudio.cs.MQuaternion _leftRotation;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"leftRotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.gamestudio.cs.MQuaternion leftRotation
    {
      get { return _leftRotation; }
      set { _leftRotation = value; }
    }
    private com.gamestudio.cs.MQuaternion _rightRotation;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"rightRotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.gamestudio.cs.MQuaternion rightRotation
    {
      get { return _rightRotation; }
      set { _rightRotation = value; }
    }
    private com.gamestudio.cs.MQuaternion _headRotation;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"headRotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.gamestudio.cs.MQuaternion headRotation
    {
      get { return _headRotation; }
      set { _headRotation = value; }
    }
    private int _moveState = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"moveState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int moveState
    {
      get { return _moveState; }
      set { _moveState = value; }
    }
    private float _posY = default(float);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float posY
    {
      get { return _posY; }
      set { _posY = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MFightRoom")]
  public partial class MFightRoom : global::ProtoBuf.IExtensible
  {
    public MFightRoom() {}
    
    private readonly global::System.Collections.Generic.List<com.gamestudio.cs.MFightUnit> _fightUnits = new global::System.Collections.Generic.List<com.gamestudio.cs.MFightUnit>();
    [global::ProtoBuf.ProtoMember(1, Name=@"fightUnits", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.gamestudio.cs.MFightUnit> fightUnits
    {
      get { return _fightUnits; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeightSet")]
  public partial class HeightSet : global::ProtoBuf.IExtensible
  {
    public HeightSet() {}
    
    private int _height;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int height
    {
      get { return _height; }
      set { _height = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTeleporter")]
  public partial class MTeleporter : global::ProtoBuf.IExtensible
  {
    public MTeleporter() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _accessIndex = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"accessIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> accessIndex
    {
      get { return _accessIndex; }
    }
  
    private com.gamestudio.cs.TeleporterStatus _status = com.gamestudio.cs.TeleporterStatus.EMPTY;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.gamestudio.cs.TeleporterStatus.EMPTY)]
    public com.gamestudio.cs.TeleporterStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    private com.gamestudio.cs.TeleporterType _type = com.gamestudio.cs.TeleporterType.BIRTH;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.gamestudio.cs.TeleporterType.BIRTH)]
    public com.gamestudio.cs.TeleporterType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private com.gamestudio.cs.MVector _position;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.gamestudio.cs.MVector position
    {
      get { return _position; }
      set { _position = value; }
    }
    private int _scorePointId = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"scorePointId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int scorePointId
    {
      get { return _scorePointId; }
      set { _scorePointId = value; }
    }
    private int _occupyCampIndex = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"occupyCampIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int occupyCampIndex
    {
      get { return _occupyCampIndex; }
      set { _occupyCampIndex = value; }
    }
    private long _occupyBeginTime = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"occupyBeginTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long occupyBeginTime
    {
      get { return _occupyBeginTime; }
      set { _occupyBeginTime = value; }
    }
    private long _occupyEndTime = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"occupyEndTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long occupyEndTime
    {
      get { return _occupyEndTime; }
      set { _occupyEndTime = value; }
    }
    private int _curCampIndex = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"curCampIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int curCampIndex
    {
      get { return _curCampIndex; }
      set { _curCampIndex = value; }
    }
    private com.gamestudio.cs.MVector _endPointPos = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"endPointPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.gamestudio.cs.MVector endPointPos
    {
      get { return _endPointPos; }
      set { _endPointPos = value; }
    }
    private int _moveSpeed = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"moveSpeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int moveSpeed
    {
      get { return _moveSpeed; }
      set { _moveSpeed = value; }
    }
    private int _birthCamp = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"birthCamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int birthCamp
    {
      get { return _birthCamp; }
      set { _birthCamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTeleporters")]
  public partial class MTeleporters : global::ProtoBuf.IExtensible
  {
    public MTeleporters() {}
    
    private readonly global::System.Collections.Generic.List<com.gamestudio.cs.MTeleporter> _teleporters = new global::System.Collections.Generic.List<com.gamestudio.cs.MTeleporter>();
    [global::ProtoBuf.ProtoMember(1, Name=@"teleporters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.gamestudio.cs.MTeleporter> teleporters
    {
      get { return _teleporters; }
    }
  
    private int _levelId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"levelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int levelId
    {
      get { return _levelId; }
      set { _levelId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TeleporterSync")]
  public partial class TeleporterSync : global::ProtoBuf.IExtensible
  {
    public TeleporterSync() {}
    
    private readonly global::System.Collections.Generic.List<com.gamestudio.cs.MTeleporter> _teleporters = new global::System.Collections.Generic.List<com.gamestudio.cs.MTeleporter>();
    [global::ProtoBuf.ProtoMember(1, Name=@"teleporters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.gamestudio.cs.MTeleporter> teleporters
    {
      get { return _teleporters; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInstantMove")]
  public partial class PlayerInstantMove : global::ProtoBuf.IExtensible
  {
    public PlayerInstantMove() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _targetIndex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"targetIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetIndex
    {
      get { return _targetIndex; }
      set { _targetIndex = value; }
    }
    private com.gamestudio.cs.MVector _targetPoint;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"targetPoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.gamestudio.cs.MVector targetPoint
    {
      get { return _targetPoint; }
      set { _targetPoint = value; }
    }
    private com.gamestudio.cs.MVector _currentPos;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"currentPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.gamestudio.cs.MVector currentPos
    {
      get { return _currentPos; }
      set { _currentPos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MemberLeave")]
  public partial class MemberLeave : global::ProtoBuf.IExtensible
  {
    public MemberLeave() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FireInfo")]
  public partial class FireInfo : global::ProtoBuf.IExtensible
  {
    public FireInfo() {}
    
    private int _targetUnitId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetUnitId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int targetUnitId
    {
      get { return _targetUnitId; }
      set { _targetUnitId = value; }
    }
    private com.gamestudio.cs.MVector _triggerPos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"triggerPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.gamestudio.cs.MVector triggerPos
    {
      get { return _triggerPos; }
      set { _triggerPos = value; }
    }
    private int _shooterId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"shooterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shooterId
    {
      get { return _shooterId; }
      set { _shooterId = value; }
    }
    private com.gamestudio.cs.DriverInfo _shooterDrive = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"shooterDrive", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.gamestudio.cs.DriverInfo shooterDrive
    {
      get { return _shooterDrive; }
      set { _shooterDrive = value; }
    }
    private com.gamestudio.cs.MQuaternion _triggerRotation;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"triggerRotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.gamestudio.cs.MQuaternion triggerRotation
    {
      get { return _triggerRotation; }
      set { _triggerRotation = value; }
    }
    private com.gamestudio.cs.CharacterPart _triggerPart = com.gamestudio.cs.CharacterPart.NONE;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"triggerPart", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.gamestudio.cs.CharacterPart.NONE)]
    public com.gamestudio.cs.CharacterPart triggerPart
    {
      get { return _triggerPart; }
      set { _triggerPart = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HarmInfo")]
  public partial class HarmInfo : global::ProtoBuf.IExtensible
  {
    public HarmInfo() {}
    
    private int _unitId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"unitId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int unitId
    {
      get { return _unitId; }
      set { _unitId = value; }
    }
    private int _originHealth;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"originHealth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int originHealth
    {
      get { return _originHealth; }
      set { _originHealth = value; }
    }
    private int _curHealth;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"curHealth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int curHealth
    {
      get { return _curHealth; }
      set { _curHealth = value; }
    }
    private com.gamestudio.cs.MVector _hurtPos;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hurtPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.gamestudio.cs.MVector hurtPos
    {
      get { return _hurtPos; }
      set { _hurtPos = value; }
    }
    private com.gamestudio.cs.MQuaternion _hurtQuaternion;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"hurtQuaternion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.gamestudio.cs.MQuaternion hurtQuaternion
    {
      get { return _hurtQuaternion; }
      set { _hurtQuaternion = value; }
    }
    private com.gamestudio.cs.CharacterPart _triggerPart;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"triggerPart", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.gamestudio.cs.CharacterPart triggerPart
    {
      get { return _triggerPart; }
      set { _triggerPart = value; }
    }
    private int _shooterId;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"shooterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shooterId
    {
      get { return _shooterId; }
      set { _shooterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeadInfo")]
  public partial class DeadInfo : global::ProtoBuf.IExtensible
  {
    public DeadInfo() {}
    
    private long _deadTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"deadTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long deadTime
    {
      get { return _deadTime; }
      set { _deadTime = value; }
    }
    private int _unitId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"unitId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int unitId
    {
      get { return _unitId; }
      set { _unitId = value; }
    }
    private long _rebirthTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rebirthTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long rebirthTime
    {
      get { return _rebirthTime; }
      set { _rebirthTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RebirthInfo")]
  public partial class RebirthInfo : global::ProtoBuf.IExtensible
  {
    public RebirthInfo() {}
    
    private int _unitId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"unitId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int unitId
    {
      get { return _unitId; }
      set { _unitId = value; }
    }
    private com.gamestudio.cs.MFightUnit _fightUnit;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fightUnit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.gamestudio.cs.MFightUnit fightUnit
    {
      get { return _fightUnit; }
      set { _fightUnit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CampScore")]
  public partial class CampScore : global::ProtoBuf.IExtensible
  {
    public CampScore() {}
    
    private int _campId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"campId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int campId
    {
      get { return _campId; }
      set { _campId = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ScoreProgress")]
  public partial class ScoreProgress : global::ProtoBuf.IExtensible
  {
    public ScoreProgress() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private long _endTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ScoreBreak")]
  public partial class ScoreBreak : global::ProtoBuf.IExtensible
  {
    public ScoreBreak() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private long _breakTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"breakTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long breakTime
    {
      get { return _breakTime; }
      set { _breakTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ScoreGet")]
  public partial class ScoreGet : global::ProtoBuf.IExtensible
  {
    public ScoreGet() {}
    
    private int _campId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"campId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int campId
    {
      get { return _campId; }
      set { _campId = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _campScore;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"campScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int campScore
    {
      get { return _campScore; }
      set { _campScore = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TimeSync")]
  public partial class TimeSync : global::ProtoBuf.IExtensible
  {
    public TimeSync() {}
    
    private long _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MChangeWeapon")]
  public partial class MChangeWeapon : global::ProtoBuf.IExtensible
  {
    public MChangeWeapon() {}
    
    private int _unitid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"unitid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int unitid
    {
      get { return _unitid; }
      set { _unitid = value; }
    }
    private int _weaponid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"weaponid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int weaponid
    {
      get { return _weaponid; }
      set { _weaponid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MCampSettleInfo")]
  public partial class MCampSettleInfo : global::ProtoBuf.IExtensible
  {
    public MCampSettleInfo() {}
    
    private int _campid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"campid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int campid
    {
      get { return _campid; }
      set { _campid = value; }
    }
    private readonly global::System.Collections.Generic.List<com.gamestudio.cs.MFightUnitSettleInfo> _fightUnitSettleInfo = new global::System.Collections.Generic.List<com.gamestudio.cs.MFightUnitSettleInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"fightUnitSettleInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.gamestudio.cs.MFightUnitSettleInfo> fightUnitSettleInfo
    {
      get { return _fightUnitSettleInfo; }
    }
  
    private int _occupyCount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"occupyCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int occupyCount
    {
      get { return _occupyCount; }
      set { _occupyCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MFightUnitSettleInfo")]
  public partial class MFightUnitSettleInfo : global::ProtoBuf.IExtensible
  {
    public MFightUnitSettleInfo() {}
    
    private int _playerid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private int _killCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"killCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int killCount
    {
      get { return _killCount; }
      set { _killCount = value; }
    }
    private int _deathCount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"deathCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int deathCount
    {
      get { return _deathCount; }
      set { _deathCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MBattleSettle")]
  public partial class MBattleSettle : global::ProtoBuf.IExtensible
  {
    public MBattleSettle() {}
    
    private int _winnerCamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"winnerCamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int winnerCamp
    {
      get { return _winnerCamp; }
      set { _winnerCamp = value; }
    }
    private readonly global::System.Collections.Generic.List<com.gamestudio.cs.MCampSettleInfo> _campSettleInfo = new global::System.Collections.Generic.List<com.gamestudio.cs.MCampSettleInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"campSettleInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.gamestudio.cs.MCampSettleInfo> campSettleInfo
    {
      get { return _campSettleInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MWeapon")]
  public partial class MWeapon : global::ProtoBuf.IExtensible
  {
    public MWeapon() {}
    
    private int _weaponid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"weaponid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int weaponid
    {
      get { return _weaponid; }
      set { _weaponid = value; }
    }
    private int _bullet;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bullet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bullet
    {
      get { return _bullet; }
      set { _bullet = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GlobalCfg")]
  public partial class GlobalCfg : global::ProtoBuf.IExtensible
  {
    public GlobalCfg() {}
    
    private int _gameTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gameTime
    {
      get { return _gameTime; }
      set { _gameTime = value; }
    }
    private int _teamMemSize;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"teamMemSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int teamMemSize
    {
      get { return _teamMemSize; }
      set { _teamMemSize = value; }
    }
    private int _rebirthTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rebirthTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rebirthTime
    {
      get { return _rebirthTime; }
      set { _rebirthTime = value; }
    }
    private int _moveCd;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"moveCd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moveCd
    {
      get { return _moveCd; }
      set { _moveCd = value; }
    }
    private int _playerHp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"playerHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerHp
    {
      get { return _playerHp; }
      set { _playerHp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TeleporterMove")]
  public partial class TeleporterMove : global::ProtoBuf.IExtensible
  {
    public TeleporterMove() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private com.gamestudio.cs.MVector _targetPos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"targetPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.gamestudio.cs.MVector targetPos
    {
      get { return _targetPos; }
      set { _targetPos = value; }
    }
    private int _moveSpeed;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"moveSpeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moveSpeed
    {
      get { return _moveSpeed; }
      set { _moveSpeed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTeleporterMoveTime")]
  public partial class MTeleporterMoveTime : global::ProtoBuf.IExtensible
  {
    public MTeleporterMoveTime() {}
    
    private long _beginMoveTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"beginMoveTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long beginMoveTime
    {
      get { return _beginMoveTime; }
      set { _beginMoveTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"UnitType")]
    public enum UnitType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER", Value=1)]
      PLAYER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROBOT", Value=2)]
      ROBOT = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TeleporterStatus")]
    public enum TeleporterStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EMPTY", Value=1)]
      EMPTY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OCCUPY", Value=2)]
      OCCUPY = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TeleporterType")]
    public enum TeleporterType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BIRTH", Value=1)]
      BIRTH = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FREE", Value=2)]
      FREE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCORE", Value=3)]
      SCORE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AUTO_MOVE", Value=4)]
      AUTO_MOVE = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CharacterPart")]
    public enum CharacterPart
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=0)]
      NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BODY", Value=1)]
      BODY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HEAD", Value=2)]
      HEAD = 2
    }
  
}