//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Ctrl.proto
namespace com.leke
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InitReq")]
  public partial class InitReq : global::ProtoBuf.IExtensible
  {
    public InitReq() {}
    
    private string _clientAddr;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clientAddr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string clientAddr
    {
      get { return _clientAddr; }
      set { _clientAddr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InitResp")]
  public partial class InitResp : global::ProtoBuf.IExtensible
  {
    public InitResp() {}
    
    private bool _needCreateRoom;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"needCreateRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool needCreateRoom
    {
      get { return _needCreateRoom; }
      set { _needCreateRoom = value; }
    }
    private string _curRoomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"curRoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string curRoomId
    {
      get { return _curRoomId; }
      set { _curRoomId = value; }
    }
    private int _allocateIndex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"allocateIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int allocateIndex
    {
      get { return _allocateIndex; }
      set { _allocateIndex = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _activeIndexList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"activeIndexList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> activeIndexList
    {
      get { return _activeIndexList; }
    }
  
    private string _allocatePhotonAddress;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"allocatePhotonAddress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string allocatePhotonAddress
    {
      get { return _allocatePhotonAddress; }
      set { _allocatePhotonAddress = value; }
    }
    private int _defaultCamp = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"defaultCamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int defaultCamp
    {
      get { return _defaultCamp; }
      set { _defaultCamp = value; }
    }
    private int _gameTime = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"gameTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameTime
    {
      get { return _gameTime; }
      set { _gameTime = value; }
    }
    private string _playerName = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private int _defaultWeapon = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"defaultWeapon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int defaultWeapon
    {
      get { return _defaultWeapon; }
      set { _defaultWeapon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeCamp")]
  public partial class ChangeCamp : global::ProtoBuf.IExtensible
  {
    public ChangeCamp() {}
    
    private int _playerIndex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerIndex
    {
      get { return _playerIndex; }
      set { _playerIndex = value; }
    }
    private int _targetCamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"targetCamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetCamp
    {
      get { return _targetCamp; }
      set { _targetCamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeWeapon")]
  public partial class ChangeWeapon : global::ProtoBuf.IExtensible
  {
    public ChangeWeapon() {}
    
    private int _playerIndex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerIndex
    {
      get { return _playerIndex; }
      set { _playerIndex = value; }
    }
    private int _targetWeapon;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"targetWeapon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetWeapon
    {
      get { return _targetWeapon; }
      set { _targetWeapon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeName")]
  public partial class ChangeName : global::ProtoBuf.IExtensible
  {
    public ChangeName() {}
    
    private string _playerName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomCreateRet")]
  public partial class RoomCreateRet : global::ProtoBuf.IExtensible
  {
    public RoomCreateRet() {}
    
    private string _curRoomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"curRoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string curRoomId
    {
      get { return _curRoomId; }
      set { _curRoomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeartBeat")]
  public partial class HeartBeat : global::ProtoBuf.IExtensible
  {
    public HeartBeat() {}
    
    private float _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameStateSync")]
  public partial class GameStateSync : global::ProtoBuf.IExtensible
  {
    public GameStateSync() {}
    
    private com.leke.GameState _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.leke.GameState state
    {
      get { return _state; }
      set { _state = value; }
    }
    private bool _video = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"video", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool video
    {
      get { return _video; }
      set { _video = value; }
    }
    private int _playerCount = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"playerCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerCount
    {
      get { return _playerCount; }
      set { _playerCount = value; }
    }
    private int _mapId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private int _camp = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int camp
    {
      get { return _camp; }
      set { _camp = value; }
    }
    private string _playerName = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChooseGameProc")]
  public partial class ChooseGameProc : global::ProtoBuf.IExtensible
  {
    public ChooseGameProc() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private string _roomName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnChooseGameProc")]
  public partial class UnChooseGameProc : global::ProtoBuf.IExtensible
  {
    public UnChooseGameProc() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameScoreUnit")]
  public partial class GameScoreUnit : global::ProtoBuf.IExtensible
  {
    public GameScoreUnit() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameScoreInfo")]
  public partial class GameScoreInfo : global::ProtoBuf.IExtensible
  {
    public GameScoreInfo() {}
    
    private readonly global::System.Collections.Generic.List<com.leke.GameScoreUnit> _scoreUnits = new global::System.Collections.Generic.List<com.leke.GameScoreUnit>();
    [global::ProtoBuf.ProtoMember(1, Name=@"scoreUnits", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.leke.GameScoreUnit> scoreUnits
    {
      get { return _scoreUnits; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterGame")]
  public partial class EnterGame : global::ProtoBuf.IExtensible
  {
    public EnterGame() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GameState")]
    public enum GameState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=1)]
      NONE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PREPARE", Value=2)]
      PREPARE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOVIE", Value=3)]
      MOVIE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"START", Value=4)]
      START = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STORY_STAGE_1", Value=5)]
      STORY_STAGE_1 = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYING", Value=6)]
      PLAYING = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STORY_STAGE_2", Value=7)]
      STORY_STAGE_2 = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENDING", Value=8)]
      ENDING = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STOP", Value=9)]
      STOP = 9
    }
  
}