//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ErrorMsg.proto
namespace com.gamestudio.room
{
    [global::ProtoBuf.ProtoContract(Name=@"ErrMsg")]
    public enum ErrMsg
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROOM_NOT_Exist", Value=1001)]
      ROOM_NOT_Exist = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROOM_FULL", Value=1002)]
      ROOM_FULL = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ROOM_OWNER", Value=1003)]
      NOT_ROOM_OWNER = 1003
    }
  
}