//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GameOperation.proto
namespace com.gamestudio.cs
{
    [global::ProtoBuf.ProtoContract(Name=@"GameOper")]
    public enum GameOper
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TELEPORTER_SYNC", Value=1001)]
      TELEPORTER_SYNC = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_INFO_SELF_INIT", Value=1002)]
      PLAYER_INFO_SELF_INIT = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAER_INFO_OTHER_INIT", Value=1003)]
      PLAER_INFO_OTHER_INIT = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAP_LOAD_SUC", Value=1004)]
      MAP_LOAD_SUC = 1004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_INSTANT_MOVE", Value=1005)]
      PLAYER_INSTANT_MOVE = 1005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_NEW", Value=1006)]
      PLAYER_NEW = 1006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIGHT_UNIT_SYNC", Value=1007)]
      FIGHT_UNIT_SYNC = 1007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MEMBER_LEAVE", Value=1008)]
      MEMBER_LEAVE = 1008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DRIVER_INFO_SYNC", Value=1009)]
      DRIVER_INFO_SYNC = 1009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SET_HEIGHT", Value=1010)]
      SET_HEIGHT = 1010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIRE", Value=1011)]
      FIRE = 1011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIT_DEAD", Value=1012)]
      UNIT_DEAD = 1012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIT_REBIRTH", Value=1013)]
      UNIT_REBIRTH = 1013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIT_HARMED", Value=1014)]
      UNIT_HARMED = 1014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCORE_BEGIN", Value=1015)]
      SCORE_BEGIN = 1015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCORE_BREAK", Value=1016)]
      SCORE_BREAK = 1016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCORE_GET", Value=1017)]
      SCORE_GET = 1017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHANGE_WEAPON", Value=1018)]
      CHANGE_WEAPON = 1018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TELEPORTER_INIT", Value=1019)]
      TELEPORTER_INIT = 1019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SETTLE_INFO", Value=1020)]
      SETTLE_INFO = 1020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WEAPON_SYNC", Value=1021)]
      WEAPON_SYNC = 1021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FILL_BULLETS", Value=1022)]
      FILL_BULLETS = 1022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOVABLE_TELEPORTER_BEGIN_TIME", Value=1023)]
      MOVABLE_TELEPORTER_BEGIN_TIME = 1023
    }
  
}