//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Record.proto
namespace com.leke.redSea
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerRecord")]
  public partial class PlayerRecord : global::ProtoBuf.IExtensible
  {
    public PlayerRecord() {}
    
    private int _Index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Index
    {
      get { return _Index; }
      set { _Index = value; }
    }
    private int _Kills;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Kills", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Kills
    {
      get { return _Kills; }
      set { _Kills = value; }
    }
    private int _Deads;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Deads", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Deads
    {
      get { return _Deads; }
      set { _Deads = value; }
    }
    private int _HeadShots;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"HeadShots", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int HeadShots
    {
      get { return _HeadShots; }
      set { _HeadShots = value; }
    }
    private int _winScore;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"winScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int winScore
    {
      get { return _winScore; }
      set { _winScore = value; }
    }
    private int _Camp;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Camp
    {
      get { return _Camp; }
      set { _Camp = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameRecordInfo")]
  public partial class GameRecordInfo : global::ProtoBuf.IExtensible
  {
    public GameRecordInfo() {}
    
    private readonly global::System.Collections.Generic.List<com.leke.redSea.PlayerRecord> _playerRecords = new global::System.Collections.Generic.List<com.leke.redSea.PlayerRecord>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playerRecords", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.leke.redSea.PlayerRecord> playerRecords
    {
      get { return _playerRecords; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"RecordType")]
    public enum RecordType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"KILL", Value=1)]
      KILL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HEADSHOT", Value=2)]
      HEADSHOT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEAD", Value=3)]
      DEAD = 3
    }
  
}