//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Room.proto
namespace com.gamestudio.room
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoom")]
  public partial class CreateRoom : global::ProtoBuf.IExtensible
  {
    public CreateRoom() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _size;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int size
    {
      get { return _size; }
      set { _size = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoom_Ret")]
  public partial class CreateRoom_Ret : global::ProtoBuf.IExtensible
  {
    public CreateRoom_Ret() {}
    
    private com.gamestudio.room.RoomInfo _roomInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.gamestudio.room.RoomInfo roomInfo
    {
      get { return _roomInfo; }
      set { _roomInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomInfo")]
  public partial class RoomInfo : global::ProtoBuf.IExtensible
  {
    public RoomInfo() {}
    
    private int _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private string _roomName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private int _maxSize;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"maxSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxSize
    {
      get { return _maxSize; }
      set { _maxSize = value; }
    }
    private int _currentSize;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"currentSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currentSize
    {
      get { return _currentSize; }
      set { _currentSize = value; }
    }
    private string _roomIp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"roomIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomIp
    {
      get { return _roomIp; }
      set { _roomIp = value; }
    }
    private int _roomPort;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"roomPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomPort
    {
      get { return _roomPort; }
      set { _roomPort = value; }
    }
    private int _mapLevel = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"mapLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mapLevel
    {
      get { return _mapLevel; }
      set { _mapLevel = value; }
    }
    private com.gamestudio.room.FightType _roomFightType = com.gamestudio.room.FightType.TEAM_BATTLE;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"roomFightType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.gamestudio.room.FightType.TEAM_BATTLE)]
    public com.gamestudio.room.FightType roomFightType
    {
      get { return _roomFightType; }
      set { _roomFightType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomInfos")]
  public partial class RoomInfos : global::ProtoBuf.IExtensible
  {
    public RoomInfos() {}
    
    private readonly global::System.Collections.Generic.List<com.gamestudio.room.RoomInfo> _roomInfos = new global::System.Collections.Generic.List<com.gamestudio.room.RoomInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"roomInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.gamestudio.room.RoomInfo> roomInfos
    {
      get { return _roomInfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinRoom")]
  public partial class JoinRoom : global::ProtoBuf.IExtensible
  {
    public JoinRoom() {}
    
    private int _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Login")]
  public partial class Login : global::ProtoBuf.IExtensible
  {
    public Login() {}
    
    private string _puid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"puid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string puid
    {
      get { return _puid; }
      set { _puid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRet")]
  public partial class LoginRet : global::ProtoBuf.IExtensible
  {
    public LoginRet() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomOper")]
  public partial class RoomOper : global::ProtoBuf.IExtensible
  {
    public RoomOper() {}
    
    private int _operid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"operid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int operid
    {
      get { return _operid; }
      set { _operid = value; }
    }
    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildUdpSession")]
  public partial class BuildUdpSession : global::ProtoBuf.IExtensible
  {
    public BuildUdpSession() {}
    
    private string _puid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"puid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string puid
    {
      get { return _puid; }
      set { _puid = value; }
    }
    private int _roomid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomid
    {
      get { return _roomid; }
      set { _roomid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MKickOff")]
  public partial class MKickOff : global::ProtoBuf.IExtensible
  {
    public MKickOff() {}
    
    private int _playerid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private string _reason = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"FightType")]
    public enum FightType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM_BATTLE", Value=1)]
      TEAM_BATTLE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEATH_BATTLE", Value=2)]
      DEATH_BATTLE = 2
    }
  
}