//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SysOperation.proto
namespace com.gamestudio.cs
{
    [global::ProtoBuf.ProtoContract(Name=@"SysOper")]
    public enum SysOper
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_TIME_SYNC", Value=3001)]
      SERVER_TIME_SYNC = 3001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ASSIGN_CLIENT_HOST", Value=2001)]
      ASSIGN_CLIENT_HOST = 2001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_AI_ROBOT", Value=2002)]
      CREATE_AI_ROBOT = 2002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYNC_ROBOT", Value=2003)]
      SYNC_ROBOT = 2003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOOT_ROBOT", Value=2004)]
      SHOOT_ROBOT = 2004
    }
  
}