//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SysOp.proto
namespace com.gamestudio.sys
{
    [global::ProtoBuf.ProtoContract(Name=@"SysOpCode")]
    public enum SysOpCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_ROOM_C", Value=101)]
      CREATE_ROOM_C = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_ROOM_S", Value=102)]
      CREATE_ROOM_S = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_C", Value=103)]
      LOGIN_C = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_S", Value=104)]
      LOGIN_S = 104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_ROOM_INFO_C", Value=105)]
      GET_ROOM_INFO_C = 105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_ROOM_INFO_S", Value=106)]
      GET_ROOM_INFO_S = 106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JOIN_ROOM_C", Value=107)]
      JOIN_ROOM_C = 107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JOIN_ROOM_S", Value=108)]
      JOIN_ROOM_S = 108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_START_C", Value=109)]
      GAME_START_C = 109,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_START_S", Value=110)]
      GAME_START_S = 110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HEIGHT_SET_C", Value=111)]
      HEIGHT_SET_C = 111,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TIME_SYNC", Value=2001)]
      TIME_SYNC = 2001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CFG_SYNC", Value=2002)]
      CFG_SYNC = 2002
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GameOpCode")]
    public enum GameOpCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPERATION", Value=1010)]
      OPERATION = 1010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_COMPLETE", Value=1011)]
      SCENE_COMPLETE = 1011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUILD_UDP_SESSION", Value=1012)]
      BUILD_UDP_SESSION = 1012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_OPERATION", Value=1013)]
      SYS_OPERATION = 1013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KICKED_OFF", Value=1014)]
      KICKED_OFF = 1014
    }
  
}